import { FormFieldProps } from "@app/types";

export const formFieldProperties: FormFieldProps = [{
  type: 'text',
  id: 'text',
  name: 'text',
  label: 'Text',
  labelClass: 'form-label',
  inputClass: 'form-control',
  placeholder: 'Enter text',
  textareaHeight: '100px',
  options: [],
  required: false,
  disabled: false,
  readOnly: false,
  value: '',
  validationRegx: null,
  errorMessage: '',
  style: {},
  onChange: (e) => e.target.value,
  onClick: (e) => e.target.value,
}];
export const formFieldPropsArray = Object.keys(formFieldProperties);
export default formFieldProperties;
console.log('FormFieldAttributes', formFieldProperties);
/* 
'id',
  'name',
  'label',
  'type',
  'placeholder',
  'required',
  'disabled',
  'options',
  'value',
  'min',
  'max',
  'step',
  'multiple',
  'rows',
  'cols',
  'minlength',
  'maxlength',
  'pattern',
  'autocomplete',
  'autofocus',
  'readonly',
  'size',
  'accept',
  'capture',
  'form',
  'formaction',
  'formenctype',
  'formmethod',
  'formnovalidate',
  'formtarget',
  'height',
  'width',
  'alt',
  'src',
  'usemap',
  'ismap',
  'longdesc',
  'crossorigin',
  'referrerpolicy',
  'sizes',
  'srcset',
  'type',
  'value',
  'checked',
  'defaultChecked',
  'defaultValue',
  'selected',
  'defaultSelected',
  'multiple',
  'size',
  'accept',
  'autocomplete',
  'autofocus',
  'capture',
  'disabled',
  'form',
  'formAction',
  'formEncType',
  'formMethod',
  'formNoValidate',
  'formTarget',
  'height',
  'width',
  'list',
  'max',
  'maxLength',
  'min',
  'minLength',
  'multiple',
  'pattern',
  'placeholder',
  'readOnly',
  'required',
  'size',
  'step',
  'type',
  'value',
  'cols',
  'rows',
  'wrap',
  'cite',
  'href',
  'target',
  'download',
  'rel',
  'hreflang',
  'type',
  'referrerpolicy',
  'as',
  'crossorigin',
  'integrity',
  'media',
  'nonce',
  'sizes',
  'src',
  'srcset',
  'usemap',
  'alt',
  'coords',
  'shape',
  'longdesc',
  'ismap',
  'loading',
  'referrerpolicy',
  'sizes',
  'srcset',
  'usemap',
  'alt',
  'coords',
  'shape',
  'longdesc',
  'ismap',
  'loading',


*/
