import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import TwoColumnLayout from './components/2-col-layout';

import './globals.scss';

declare function RootLayout({ children, }: Readonly<{
  children?: React.ReactNode;
}>): JSX.Element

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export const viewPort: Viewport = {
  initialScale: 1,
  width: 'device-width'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  ;
  
  return (
    <html lang='en' data-bs-theme='dark'>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TwoColumnLayout>
          {children}
        </TwoColumnLayout>
        
      </body>
    </html>
  );
}
